import { createAction, createSlice} from "@reduxjs/toolkit"
import { IBlog } from "../../types/backend";

export interface BlogState {
    isPending: boolean,
    isError: boolean,
    data: IBlog[],
    errors: string,

    isCreating: boolean,
    isCreatingSuccess: boolean,

    isUpdating: boolean,
    isUpdatingSuccess: boolean,

    isDeleting: boolean,
    isDeletingSuccess: boolean,
}

const initialState: BlogState = {
    isPending: false,
    isError: false,
    data: [ ],
    errors: "",

    isCreating: false,
    isCreatingSuccess: false,

    isUpdating: false,
    isUpdatingSuccess: false,


    isDeleting: false,
    isDeletingSuccess: false,
}
export const incrementSagaFinish = createAction<{value: number}>("blog/incrementSagaFinish");

export const fetchBlogPending = createAction("blog/fetchBlogPending");
export const fetchBlogSuccess = createAction<{data: IBlog[]}>("blog/fetchBlogSuccess");
export const fetchBlogError = createAction<{errors: string}>("blog/fetchBlogError");

export const createBlogPending = createAction<{title: string; content: string; author: string}>("blog/createBlogPending");
export const createBlogSuccess = createAction("blog/createBlogSuccess");
export const createBlogError = createAction<{errors: string}>("blog/createBlogError");

export const updateBlogPending = createAction<{id: number; title: string; content: string; author: string}>("blog/updateBlogPending");
export const updateBlogSuccess = createAction("blog/updateBlogSuccess");
export const updateBlogError = createAction<{errors: string}>("blog/updateBlogError");

export const deleteBlogPending = createAction<{id: number}>("blog/deleteBlogPending");
export const deleteBlogSuccess = createAction("blog/deleteBlogSuccess");
export const deleteBlogError = createAction<{errors: string}>("blog/deleteBlogError");

export const blogSlice = createSlice({
    name: "blog",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchBlogPending, (state) => {
                state.isPending = true;
                state.isError = false;
            })
            .addCase(fetchBlogSuccess, (state, action) => {
                state.isPending = false;
                state.isError = false;
                state.data = action.payload.data;
                // console.log("fetchBlogSuccess is running", state.data);
            })
            .addCase(fetchBlogError, (state, action) => {
                state.isPending = false;
                state.isError = true;
                state.errors = action?.payload?.errors;   
            })
            .addCase(createBlogPending, (state) => {
                state.isCreating = true;
                state.isCreatingSuccess = false;
            })
            .addCase(createBlogSuccess, (state) => {
                state.isCreating = false;
                state.isCreatingSuccess = true;
            })
            .addCase(updateBlogPending, (state) => {
                state.isUpdating = true;
                state.isUpdatingSuccess = false;
            })
            .addCase(updateBlogSuccess, (state) => {
                state.isUpdating = false;
                state.isUpdatingSuccess = true;
            })
            .addCase(updateBlogError, (state, action) => {
                state.isUpdating = false;
                state.isUpdatingSuccess = false;
                state.errors = action?.payload?.errors;
            })
            .addCase(deleteBlogPending, (state) => {
                state.isDeleting = true;
                state.isDeletingSuccess = false;
            })
            .addCase(deleteBlogSuccess, (state) => {
                state.isDeleting = false;
                state.isDeletingSuccess = true;
            })
            .addCase(deleteBlogError, (state, action) => {
                state.isDeleting = false;
                state.isDeletingSuccess = false;
                state.errors = action?.payload?.errors;
            })

    },
})

export const { } = blogSlice.actions


export default blogSlice.reducer
