import { createAction, createSlice} from "@reduxjs/toolkit"
import { ILogin, IUser } from "../../types/backend";

export interface UserState {
    isPending: boolean,
    isError: boolean,
    data: IUser[],
    errors: string,

    isCreating: boolean,
    isCreatingSuccess: boolean,

    isUpdating: boolean,
    isUpdatingSuccess: boolean,

    isDeleting: boolean,
    isDeletingSuccess: boolean,
}

const initialState: UserState = {
    isPending: false,
    isError: false,
    data: [ ],
    errors: "",

    isCreating: false,
    isCreatingSuccess: false,

    isUpdating: false,
    isUpdatingSuccess: false,


    isDeleting: false,
    isDeletingSuccess: false,
}

export const loginPending = createAction<ILogin>("auth/loginPending");
export const logout = createAction("auth/logout");
export const fetchUserPending = createAction("user/fetchUserPending");
export const fetchUserSuccess = createAction<{data: IUser[]}>("user/fetchUserSuccess");
export const fetchUserError = createAction<{errors: string}>("user/fetchUserError");

export const createUserPending = createAction<{email: string; name: string}>("user/createUserPending");
export const createUserSuccess = createAction("user/createUserSuccess");
export const createUserError = createAction<{errors: string}>("user/createUserError");

export const updateUserPending = createAction<{id: number; email: string; name: string}>("user/updateUserPending");
export const updateUserSuccess = createAction("user/updateUserSuccess");
export const updateUserError = createAction<{errors: string}>("user/updateUserError");

export const deleteUserPending = createAction<{id: number}>("user/deleteUserPending");
export const deleteUserSuccess = createAction("user/deleteUserSuccess");
export const deleteUserError = createAction<{errors: string}>("user/deleteUserError");

export const userSlice = createSlice({
    name: "user",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUserPending, (state) => {
                state.isPending = true;
                state.isError = false;
            })
            .addCase(fetchUserSuccess, (state, action) => {
                state.isPending = false;
                state.isError = false;
                state.data = action.payload.data;
                // console.log("fetchUserSuccess is running", state.data);
            })
            .addCase(fetchUserError, (state, action) => {
                state.isPending = false;
                state.isError = true;
                state.errors = action?.payload?.errors;   
            })
            .addCase(createUserPending, (state) => {
                state.isCreating = true;
                state.isCreatingSuccess = false;
            })
            .addCase(createUserSuccess, (state) => {
                state.isCreating = false;
                state.isCreatingSuccess = true;
            })
            .addCase(updateUserPending, (state) => {
                state.isUpdating = true;
                state.isUpdatingSuccess = false;
            })
            .addCase(updateUserSuccess, (state) => {
                state.isUpdating = false;
                state.isUpdatingSuccess = true;
            })
            .addCase(updateUserError, (state, action) => {
                state.isUpdating = false;
                state.isUpdatingSuccess = false;
                state.errors = action?.payload?.errors;
            })
            .addCase(deleteUserPending, (state) => {
                state.isDeleting = true;
                state.isDeletingSuccess = false;
            })
            .addCase(deleteUserSuccess, (state) => {
                state.isDeleting = false;
                state.isDeletingSuccess = true;
            })
            .addCase(deleteUserError, (state, action) => {
                state.isDeleting = false;
                state.isDeletingSuccess = false;
                state.errors = action?.payload?.errors;
            })

    },
})

export const { } = userSlice.actions


export default userSlice.reducer
