import { createAction, createSlice} from "@reduxjs/toolkit"
import { IUser } from "../../types/backend";

export interface UserState {
    isPending: boolean,
    isError: boolean,
    data: IUser[],
    errors: string,
}

const initialState: UserState = {
    isPending: false,
    isError: false,
    data: [ ],
    errors: "",
}
export const incrementSagaFinish = createAction<{value: number}>("user/incrementSagaFinish");

export const fetchUserPending = createAction("user/fetchUserPending");
export const fetchUserSuccess = createAction<{data: IUser[]}>("user/fetchUserSuccess");
export const fetchUserError = createAction<{errors: string}>("user/fetchUserError");

export const userSlice = createSlice({
    name: "user",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUserPending, (state) => {
                state.isPending = true;
                state.isError = false;
            })
            .addCase(fetchUserSuccess, (state, action) => {
                state.isPending = false;
                state.isError = false;
                state.data = action.payload.data;
                // console.log("fetchUserSuccess is running", state.data);
            })
            .addCase(fetchUserError, (state, action) => {
                state.isPending = false;
                state.isError = true;
                state.errors = action?.payload?.errors;   
            })
    },
})

export const { } = userSlice.actions


export default userSlice.reducer
